### ISSUE TITLE
Unable to read filterbank files with SIGPROC

### ISSUE THREAD

**Issue by mef51** [cbochenek/STARE2-analysis#1]
sigproc's `reader` and `header` programs throw an error when trying to open any of the three filterbank files:

```sh
mohammed@DESKTOP-T5ETFQ4:/mnt/b/dev/STARE2-analysis$ header candidate_delta_20200428.fil
ERROR: read_header - unknown parameter: start_sample

mohammed@DESKTOP-T5ETFQ4:/mnt/b/dev/STARE2-analysis$ header candidate_ovro_20200428.fil
ERROR: read_header - unknown parameter: start_sample

mohammed@DESKTOP-T5ETFQ4:/mnt/b/dev/STARE2-analysis$ header candidate_gdscc_20200428.fil
ERROR: read_header - unknown parameter: start_sample
```

the output is the same with `reader`.

I've been trying to install sigpyproc like in your script but it keeps failing..

**Comment by KshitijAggarwal** [comment]
We encountered the same issue when [Your](https://github.com/thepetabyteproject/your) was used to read this data https://github.com/thepetabyteproject/your/issues/56. We have implemented a fix for this which ignores those extra header parameters. [Your](https://github.com/thepetabyteproject/your) (Unified Reader) can now read this data, so try using it for the analysis.

**Comment by mef51** [comment]
Thanks. I will try it out. Chris Bochenek provided me with a modified [sigpyproc3 ](https://github.com/FRBs/sigpyproc3) file via email that defines the custom headers
